package caddy

import (
	"net/http"
	"runtime"
	"strings"

	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp/fileserver"
)

// MatchDirIndex is the request matcher used by the canonical trailing-slash
// directory-redirect route generated by the php_server directive and the
// php-server command.
//
// It is equivalent to the matcher set historically generated (mirroring
// Caddy's php_fastcgi directive):
//
//	@canonicalPath {
//	    file {path}/<index>
//	    not path */
//	}
//
// but with two performance advantages:
//
//  1. The cheap string checks are guaranteed to run BEFORE the filesystem
//     probe. Matchers inside a Caddy matcher set are evaluated in map
//     iteration order, so with the historical shape the expensive file
//     matcher could (randomly, per config load) run first even for requests
//     that the `not path */` matcher would have rejected.
//  2. Requests whose path ends in one of the PHP split extensions (".php" by
//     default) are rejected without consulting the filesystem at all. Such
//     paths could historically only match in the pathological case of a
//     directory literally named e.g. "x.php" that contains the index file.
//
// Semantics note for that pathological case: a directory named "x.php" no
// longer receives the 308 trailing-slash redirect. This is safe because such
// a directory is already shadowed by PHP handling: the split_path logic of
// the try_files rewrite that follows truncates the "/x.php/index.php"
// candidate at the split extension to "/x.php", which is a directory and not
// a file, so the candidate fails and the request falls back to the site index
// file. That is true both with and without the redirect (after the historical
// 308, the re-request for "/x.php/" went through the exact same fallback), so
// the response body is identical either way; only the intermediate redirect
// round-trip disappears.
type MatchDirIndex struct {
	// Root is the site root directory. Same semantics as the file matcher's
	// root; defaults to the `{http.vars.root}` placeholder.
	Root string `json:"root,omitempty"`
	// Index is the directory index filename to probe for, e.g. "index.php".
	Index string `json:"index,omitempty"`
	// SplitPath lists the path suffixes handled as PHP scripts (".php" by
	// default). Requests whose path ends in one of them never match.
	SplitPath []string `json:"split_path,omitempty"`
	// DisableStat disables substituting the native stat-based file matcher
	// (MatchFileStat) for the internal filesystem probe, falling back to the
	// stock fileserver.MatchFile. Wired to php_server's disable_stat_matcher
	// option.
	DisableStat bool `json:"disable_stat,omitempty"`

	file caddyhttp.RequestMatcherWithError
}

// CaddyModule returns the Caddy module information.
func (MatchDirIndex) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.matchers.php_dir_index",
		New: func() caddy.Module { return new(MatchDirIndex) },
	}
}

// Provision sets up the matcher and its underlying file matcher.
func (m *MatchDirIndex) Provision(ctx caddy.Context) error {
	if m.Index == "" {
		m.Index = "index.php"
	}
	if len(m.SplitPath) == 0 {
		m.SplitPath = []string{".php"}
	}

	stock := fileserver.MatchFile{
		Root:     m.Root,
		TryFiles: []string{"{http.request.uri.path}/" + m.Index},
	}

	// use the native stat-based matcher for the filesystem probe when a
	// semantics-preserving substitution is possible (see statmatcher.go)
	if !m.DisableStat && statMatcherSubstitutable(stock) {
		statFile := &MatchFileStat{
			Root:     stock.Root,
			TryFiles: stock.TryFiles,
		}
		if err := statFile.Provision(ctx); err != nil {
			return err
		}
		m.file = statFile

		return nil
	}

	if err := stock.Provision(ctx); err != nil {
		return err
	}
	m.file = &stock

	return nil
}

// Match returns true if r matches m.
func (m *MatchDirIndex) Match(r *http.Request) bool {
	match, _ := m.MatchWithError(r)

	return match
}

// MatchWithError returns true if r matches m.
func (m *MatchDirIndex) MatchWithError(r *http.Request) (bool, error) {
	path := r.URL.Path
	if runtime.GOOS == "windows" {
		// mirror the normalization applied by caddyhttp.MatchPath (caddy#5613)
		path = strings.ReplaceAll(path, `\`, "/")
		path = strings.TrimRight(path, ". ")
	}

	// equivalent of the `not path */` matcher: a path that already ends in a
	// slash cannot need the canonical trailing-slash redirect
	if strings.HasSuffix(path, "/") {
		return false, nil
	}

	// prefilter: paths ending in a PHP split extension never need the
	// redirect (see the type documentation), skip the filesystem probe
	for _, split := range m.SplitPath {
		if hasSuffixFold(path, split) {
			return false, nil
		}
	}

	return m.file.MatchWithError(r)
}

// hasSuffixFold reports whether s ends with suffix, ASCII-case-insensitively,
// matching the case-insensitive behavior of Caddy's path matchers.
func hasSuffixFold(s, suffix string) bool {
	return len(s) >= len(suffix) && strings.EqualFold(s[len(s)-len(suffix):], suffix)
}

// Interface guards
var (
	_ caddy.Provisioner                 = (*MatchDirIndex)(nil)
	_ caddyhttp.RequestMatcher          = (*MatchDirIndex)(nil)
	_ caddyhttp.RequestMatcherWithError = (*MatchDirIndex)(nil)
)
